export const LOAD_STATE = "LOAD_STATE";
export const LOAD_DEFAULT_STATE = "LOAD_DEFAULT_STATE";
export const SAVED = "SAVED";


export const ADD_SCHEMA = "ADD_SCHEMA";
export const REMOVE_SCHEMA = "REMOVE_SCHEMA";
export const SELECT_SCHEMA = "SELECT_SCHEMA";
export const EDIT_SCHEMA = "EDIT_SCHEMA";
export const UPDATE_SCHEMA = "UPDATE_SCHEMA";
export const UPDATE_SCHEMA_TEXT = "UPDATE_SCHEMA_TEXT";
export const UPDATE_RESULT = "UPDATE_RESULT";
export const SHOW_SCHEMA_ERROR = "SHOW_SCHEMA_ERROR";
